### ISSUE TITLE
"Ghost" artifact of other open tabs during screenshot - Ubuntu 18.04

### ISSUE THREAD

**Issue by aditya-krish** [bwoodsend/vtkplotlib#1] opened 2020-03-03 06:49 UTC
I am using Ubuntu 18.04 to run an application, which takes screenshots of a mesh. I am using Nvidia Quadro P5000 GPU with nvidia 435 proprietary driver (I also tried with with Nouveau driver which gives the same issue). 
![31535222_13_1](https://user-images.githubusercontent.com/55757328/75749938-040a4880-5d49-11ea-87e7-3831e2fa5217.jpeg)
![31535222_13_2](https://user-images.githubusercontent.com/55757328/75749942-053b7580-5d49-11ea-87a4-1484c5d06205.jpeg)

Have you encountered this before, or aware of what causes the problem? The application runs fine on windows servers, and has been tested extensively, but gives this problem in Ubuntu.

**Comment by bwoodsend** [comment] 2020-03-07 18:20
No, I've never seen that before.

Could you elaborate a bit? When you say *screenshot*, do you mean `vtkplotlib.save_fig()` or the PrtSC button on your keyboard? Am I right in saying it's the black ring-shaped thing you want to screenshot but the little windows in the bottom left that shouldn't be there?

Also can you post your VTK version (using `pip show vtk` or `conda info vtk`)?

**Comment by aditya-krish** [comment] 2020-03-07 18:24
Yeah I am using save_fig(). I am aware that it uses
vtk.vtkWindowToImageFilter() and I guess that has some OS specific code?
Yeah the black ring is what I want but I am getting those extra windows,
the pixels parameter is set to [1800,1800] if that helps.

**Comment by bwoodsend** [comment] 2020-03-07 18:41
I hate to think what a lot of these vtk classes get up to underneath. I've just tried on Ubuntu 19.10 and that's all working normally. I'd like to do some tests but firstly does it change if you change the pixels parameter or plot something different (such as `vpl.quick_test_plot()`)?

**Comment by aditya-krish** [comment] 2020-03-09 08:29
You can see the windows on the image, those "ghost" windows are all 300x300
in size, changing pixel size still brings ghost windows but they are always
300x300. So if the pixels is set to [300,300] then entire image will be one
ghost window and so on. Normal plotting and showing works fine, only
screenshot_fig and save_fig are giving trouble. When the screenshot_fig is
running, try constantly changing tabs between Firefox and activities tab to
reproduce the error. You might have to give a pause before the
screenshot_fig to make this tab change possible before screenshot is taken,
like putting this block of code before screenshot_fig:

import time
since = time.time()
while time.time() - since < 2:
    pass

**Comment by bwoodsend** [comment] 2020-03-09 11:46
OK, I've tried what you said and I can't reproduce it at all. I noticed that `screenshot_fig()` doesn't call `vtkWindowToImageFilter.Modified()` which I think it aught to and there is also off screen rendering to play with. I've done a stripped down example for you to test. Could you give it a run for me please?

```
import vtkplotlib as vpl
import vtkplotlib.image_io
import matplotlib.pylab as plt
import vtk
import time

fig = vpl.figure()
vpl.quick_test_plot()

# Try turning this one on and off and see if it changes anything.
#fig.renWin.SetOffScreenRendering(True)

since = time.time()
while time.time() - since < 2:
    pass


fig.connect()
fig.reset_camera()
fig.renWin.Render()


win2im_filter = vtk.vtkWindowToImageFilter()
win2im_filter.SetInput(fig.renWin)
win2im_filter.Modified()
win2im_filter.Update()

arr = vpl.image_io.vtkimagedata_to_array(win2im_filter.GetOutput())

win2im_filter.SetInput(None)
vpl.close(fig)

plt.imshow(arr)
plt.show()
```

**Comment by aditya-krish** [comment] 2020-03-09 13:20
I tried two things, the above routine and screenshot_fig, for the same
mesh. The above routine almost always seems to work, but screenshot_fig
almost always does not work. I am attaching the images generated by both
the routines, the one showing a tooth like structure is the above routine
on the other hand the one showing the "ghost" artifact is using
screenshot_fig.

**Comment by aditya-krish** [comment] 2020-03-09 13:22
I also tried commenting out the w2im_filter.Modified() line, that still
gives proper image, with no artifacts. So I guess it is not due to that
line.

**Comment by aditya-krish** [comment] 2020-03-09 13:23
Okay after attempting multiple times I finally got the artifact even when
using the code you have posted above.

**Comment by bwoodsend** [comment] 2020-03-09 13:45
> I am attaching the images generated by both
Either you forgot to attach or they didn't work... :)

Did you try the `fig.renWin.SetOffScreenRendering(True)` line near the top?

Also are you doing teeth as well? That's what I wrote this library for in the first place.

**Comment by aditya-krish** [comment] 2020-03-10 04:23
This following one is the correct image, output of `fig.renWin.SetOffScreenRendering(True)`:
![above_code](https://user-images.githubusercontent.com/55757328/76279097-77650a80-62b3-11ea-9cca-eeb4b9cd8806.png)

This is the bad screenshot generated by the above routine:
![above_code2](https://user-images.githubusercontent.com/55757328/76279100-78963780-62b3-11ea-9e06-da63911b2824.png)

This is the output of screenshot_fig:
![screenshot_fig](https://user-images.githubusercontent.com/55757328/76279105-792ece00-62b3-11ea-85d4-efda31586dad.png)

Yes I am working on intra-oral scans, small world!! 

The `fig.renWin.SetOffScreenRendering(True)` line seems to do the job, thanks a lot. The only issue is it is not running from the shell on the server and aborting with error "Aborting - bad X server connection." But that does not belong to this thread. I will edit the screenshot_fig in my environment to reflect this change. Thank you for your inputs.

**Comment by bwoodsend** [comment] 2020-03-10 10:27
OK, I'm glad you highlighted that. It looks like off screen rendering can get ugly. I'll pop it in the next update but as an optional parameter.

**Comment by bwoodsend** [comment] 2020-03-10 11:09
Could you do me a favour and keep me posted on your resolving that *bad X-server* issue? I'd like to at least add it to the docs if it's not practical to fix outright.

**Comment by aditya-krish** [comment] 2020-03-10 11:27
It works when I make a GUI login to the server, open terminal and run the application. It does not work when I connect to the server through SSH. Do you want me to post a screenshot of the error?

**Comment by bwoodsend** [comment] 2020-03-10 11:47
Might as well although I doubt I can help much. I did a google of "Aborting - bad X server connection" and [this comment](https://discourse.vtk.org/t/how-to-build-vtk-on-a-supercomputer-without-x-server-and-no-root-previliges/377/4) seems to say you need a special build of VTK with OSMesa. But the fact you can get it to work via the GUI suggests you already have everything you need.

**Comment by aditya-krish** [comment] 2020-03-11 08:59
Yes I am good with the current solution, even if it doesn't work with SSH, I was just suggesting it for your documentation purposes
![bwoodsend_error_image](https://user-images.githubusercontent.com/55757328/76399518-bb840800-63a4-11ea-892f-564e2ca27c38.png)

**Comment by bwoodsend** [comment] 2020-03-11 12:53
OK. I'll leave this issue open until I've pushed and released the changes. Thanks for your help with this.

Just as a warning to future readers of this thread: The `fig.renWin.SetOffScreenRendering(True)` option seems to mess the vtkRenderWindow irreversibly so that the figure can no longer be shown normally without crashing. Calling `vpl.close(fig=fig)` after `screenhot_fig()` or `save_fig()` resets the vtkRenderWindow so that the figure can be safely reshown. Hopefully this will all be ironed out in the next release (v1.3.0) so that you shouldn't need to worry about any of this.

**Closed** 2020-03-20 21:14 UTC
